create table if not exists public.work_items (
  id bigint generated by default as identity primary key,
  leadername text not null,
  workowner text not null,
  workname text not null unique,
  deadline text not null,
  status text not null check (status in ('todo', 'progress', 'done')),
  progress integer not null default 0 check (progress >= 0 and progress <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists work_items_workname_idx on public.work_items (workname);